package me.az1.dblab.Common.DatabaseControllerCorbaPackage;


/**
* me/az1/dblab/Common/DatabaseControllerCorbaPackage/int64Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/me/az1/dblab/Common/DatabaseControllerCorba.idl
* Thursday, December 4, 2014 5:40:32 PM EET
*/

public final class int64Holder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public int64Holder ()
  {
  }

  public int64Holder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64Helper.type ();
  }

}
