package me.az1.dblab.Common.DatabaseControllerCorbaPackage;


/**
* me/az1/dblab/Common/DatabaseControllerCorbaPackage/int64arrHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/me/az1/dblab/Common/DatabaseControllerCorba.idl
* Thursday, December 4, 2014 5:40:32 PM EET
*/

public final class int64arrHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[][] = null;

  public int64arrHolder ()
  {
  }

  public int64arrHolder (int[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64arrHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64arrHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return me.az1.dblab.Common.DatabaseControllerCorbaPackage.int64arrHelper.type ();
  }

}
