package me.az1.dblab.Common;


/**
* me/az1/dblab/Common/DatabaseControllerCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/me/az1/dblab/Common/DatabaseControllerCorba.idl
* Thursday, December 4, 2014 5:40:32 PM EET
*/

public interface DatabaseControllerCorba extends DatabaseControllerCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DatabaseControllerCorba
