package me.az1.dblab.Common;

/**
* me/az1/dblab/Common/DatabaseControllerCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/me/az1/dblab/Common/DatabaseControllerCorba.idl
* Thursday, December 4, 2014 5:40:32 PM EET
*/

public final class DatabaseControllerCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public me.az1.dblab.Common.DatabaseControllerCorba value = null;

  public DatabaseControllerCorbaHolder ()
  {
  }

  public DatabaseControllerCorbaHolder (me.az1.dblab.Common.DatabaseControllerCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = me.az1.dblab.Common.DatabaseControllerCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    me.az1.dblab.Common.DatabaseControllerCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return me.az1.dblab.Common.DatabaseControllerCorbaHelper.type ();
  }

}
